name: linux
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 1 * *'
jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 3.2
  build:
    needs: ruby-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        exclude:
          - ruby: head
        os:
          - ubuntu-latest
        gemfile:
          - activesupport
          - no-activesupport
    env:
      BUNDLE_GEMFILE: spec/gemfiles/${{ matrix.gemfile }}.gemfile
    name: Ruby ${{ matrix.ruby }} unit testing on ${{ matrix.os }} (${{ matrix.gemfile }})
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: unit testing
      env:
        CI: true
      run: |
        bundle exec rake spec
